#!/bin/bash

if [ $1 = "on" ]; then
gpio -g write 4 0
# toggle the reset pin
jreset
elif [ $1 = "restart" ]; then
if [ ! -f "/boot/juicyboard.txt" ]; then
gpio -g write 4 1
sleep 15
gpio -g write 4 0
else
# just toggle the reset pin
jreset
fi
else
gpio -g write 4 1
fi
